AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  boilerplate-service

  Sample SAM Template for boilerplate-service

Parameters:
  environment:
    Description: Environment type.
    Type: String
    AllowedValues:
      - staging
      - prod
      - dev
    ConstraintDescription: must specify staging, dev or prod
  service:
    Description: Service name.
    Type: String

Globals:
  Function:
    Timeout: 3

Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Tracing: Active
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: !Ref service
          POWERTOOLS_METRICS_NAMESPACE: boilerplate-namespace
          LOG_LEVEL: INFO
      Events:
        HelloWorld:
          Type: Api
          Properties:
            RestApiId: !Ref StagingApi
            Path: /
            Method: GET
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        # Sourcemap: true # Enabling source maps will create the required NODE_OPTIONS environment variables on your lambda function during sam build
        EntryPoints:
          - app.ts

  MyFunctionLogGroup: #To ensure Logs are deleted after a while.
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${MyFunction}"
      RetentionInDays: 7

  StagingApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      DefinitionBody:
        Fn::Transform:
          Name: "AWS::Include"
          Parameters:
            Location: "./openapi.yml"
      EndpointConfiguration:
        Type: REGIONAL
      Domain:
        DomainName: !Sub "${service}.${environment}.enpalm.se"
        CertificateArn: !Sub "{{resolve:ssm:/${environment}/API/CertificateARN}}"
        Route53:
          HostedZoneName: !Sub "${environment}.enpalm.se."

Outputs:
  ServiceDomainName:
    Value: !Sub "https://${service}.${environment}.enpalm.se"
